In [ ]:
import pandas as pd
import numpy as np
import openpyxl

df = pd.read_excel("ProjetoLogisticaData.xlsx")
df_filtrado = df[df["Tipo_Local"] == "URF"]
display(df_filtrado)

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
0,Acordo Agrícola OMC e Pescados,Exportacao,2015.0,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,-,URF,0130151 - CACERES
1,Acordo Agrícola OMC e Pescados,Exportacao,2015.0,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,64,35,URF,0145100 - MUNDO NOVO
2,Acordo Agrícola OMC e Pescados,Exportacao,2015.0,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,6322760,4924826,URF,0145200 - CORUMBA
3,Acordo Agrícola OMC e Pescados,Exportacao,2015.0,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,53703,32125,URF,0145300 - PONTA PORA
4,Acordo Agrícola OMC e Pescados,Exportacao,2015.0,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,-,-,URF,0147600 - ALF - CORUMBÁ
...,...,...,...,...,...,...,...,...,...
2598,Agronegócio,Exportacao,2025.0,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,262317068,70240574,URF,1017701 - IRF - CHUÍ
2599,Agronegócio,Exportacao,2025.0,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,128546,19740,URF,1017800 - ALF - PORTO ALEGRE
2600,Agronegócio,Exportacao,2025.0,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,-,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
2601,Agronegócio,Exportacao,2025.0,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,-,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
2602,Agronegócio,Exportacao,2025.0,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,16687,55,URF,9999999 - NAO INFORMADO

In [5]:
df_filtrado.to_excel("Nova_planilha.xlsx", index = False)

In [ ]:
df_novo = pd.read_excel("Nova_planilha.xlsx")
df_novo.loc[:, 'Peso_KG'] = df_novo['Peso_KG'].replace("-", 0)
for data, df in df_novo.groupby(["Regiao_UF_URF", "Agrupamento"]):
    df: pd.DataFrame
    display(df)

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
0,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
84,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
168,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
252,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
336,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0130151 - CACERES,401301,165706,URF,0130151 - CACERES
420,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0130151 - CACERES,30762,12326,URF,0130151 - CACERES
504,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
588,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
672,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
756,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
840,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
924,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
1008,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
1092,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
1176,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
1260,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0130151 - CACERES,401301,165706,URF,0130151 - CACERES
1344,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0130151 - CACERES,30762,12326,URF,0130151 - CACERES
1428,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
1512,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
1596,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
1680,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES
1764,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,0,URF,0130151 - CACERES

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
1,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,64,35,URF,0145100 - MUNDO NOVO
85,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
169,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
253,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
337,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
421,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
505,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
589,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
673,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
757,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
841,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
925,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,64,35,URF,0145100 - MUNDO NOVO
1009,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
1093,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
1177,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
1261,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
1345,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
1429,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
1513,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
1597,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
1681,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO
1765,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,-,0,URF,0145100 - MUNDO NOVO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
2,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,6322760,4924826,URF,0145200 - CORUMBA
86,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,6474399,5553262,URF,0145200 - CORUMBA
170,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,2274041,1734296,URF,0145200 - CORUMBA
254,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
338,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
422,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
506,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
590,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
674,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
758,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
842,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
926,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,6322760,4924826,URF,0145200 - CORUMBA
1010,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,6474399,5553262,URF,0145200 - CORUMBA
1094,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,2274041,1734296,URF,0145200 - CORUMBA
1178,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
1262,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
1346,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
1430,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
1514,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
1598,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
1682,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA
1766,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,-,0,URF,0145200 - CORUMBA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
3,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,53703,32125,URF,0145300 - PONTA PORA
87,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,73309,43117,URF,0145300 - PONTA PORA
171,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,1311235,619124,URF,0145300 - PONTA PORA
255,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
339,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
423,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
507,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
591,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
675,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
759,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
843,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
927,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,53703,32125,URF,0145300 - PONTA PORA
1011,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,73309,43117,URF,0145300 - PONTA PORA
1095,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,1311235,619124,URF,0145300 - PONTA PORA
1179,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
1263,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
1347,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
1431,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
1515,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
1599,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
1683,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA
1767,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,-,0,URF,0145300 - PONTA PORA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
4,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,-,0,URF,0147600 - ALF - CORUMBÁ
88,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,-,0,URF,0147600 - ALF - CORUMBÁ
172,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,-,0,URF,0147600 - ALF - CORUMBÁ
256,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,1363238,875388,URF,0147600 - ALF - CORUMBÁ
340,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,2354133,1592158,URF,0147600 - ALF - CORUMBÁ
424,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,2501459,2375550,URF,0147600 - ALF - CORUMBÁ
508,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,3895838,4639176,URF,0147600 - ALF - CORUMBÁ
592,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,5009429,5304501,URF,0147600 - ALF - CORUMBÁ
676,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,6735004,6383205,URF,0147600 - ALF - CORUMBÁ
760,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,5370270,4981412,URF,0147600 - ALF - CORUMBÁ
844,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,4191087,4104783,URF,0147600 - ALF - CORUMBÁ

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
928,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,-,0,URF,0147600 - ALF - CORUMBÁ
1012,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,-,0,URF,0147600 - ALF - CORUMBÁ
1096,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,-,0,URF,0147600 - ALF - CORUMBÁ
1180,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,1363238,875388,URF,0147600 - ALF - CORUMBÁ
1264,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,2354133,1592158,URF,0147600 - ALF - CORUMBÁ
1348,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,2501459,2375550,URF,0147600 - ALF - CORUMBÁ
1432,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,3895838,4639176,URF,0147600 - ALF - CORUMBÁ
1516,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,5009429,5304501,URF,0147600 - ALF - CORUMBÁ
1600,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,6735004,6383205,URF,0147600 - ALF - CORUMBÁ
1684,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,5370270,4981412,URF,0147600 - ALF - CORUMBÁ
1768,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,4191087,4104783,URF,0147600 - ALF - CORUMBÁ

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
5,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,-,0,URF,0147800 - ALF - PONTA PORÃ
89,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,-,0,URF,0147800 - ALF - PONTA PORÃ
173,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,-,0,URF,0147800 - ALF - PONTA PORÃ
257,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,19878727,7569714,URF,0147800 - ALF - PONTA PORÃ
341,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,275744,207556,URF,0147800 - ALF - PONTA PORÃ
425,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,78104,37208,URF,0147800 - ALF - PONTA PORÃ
509,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,-,0,URF,0147800 - ALF - PONTA PORÃ
593,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,4669083,1492863,URF,0147800 - ALF - PONTA PORÃ
677,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,12305522,3815258,URF,0147800 - ALF - PONTA PORÃ
761,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,12788174,3834867,URF,0147800 - ALF - PONTA PORÃ
845,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,27951686,8872458,URF,0147800 - ALF - PONTA PORÃ

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
929,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,-,0,URF,0147800 - ALF - PONTA PORÃ
1013,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,-,0,URF,0147800 - ALF - PONTA PORÃ
1097,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,-,0,URF,0147800 - ALF - PONTA PORÃ
1181,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,19878727,7569714,URF,0147800 - ALF - PONTA PORÃ
1265,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,275744,207556,URF,0147800 - ALF - PONTA PORÃ
1349,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,78104,37208,URF,0147800 - ALF - PONTA PORÃ
1433,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,-,0,URF,0147800 - ALF - PONTA PORÃ
1517,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,4669083,1492863,URF,0147800 - ALF - PONTA PORÃ
1601,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,12305522,3815258,URF,0147800 - ALF - PONTA PORÃ
1685,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,12788174,3834867,URF,0147800 - ALF - PONTA PORÃ
1769,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0147800 - ALF - PONTA PORÃ,27951686,8872458,URF,0147800 - ALF - PONTA PORÃ

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
6,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,-,0,URF,0210200 - SANTAREM
90,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,-,0,URF,0210200 - SANTAREM
174,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,97312,27044,URF,0210200 - SANTAREM
258,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,35393,4974,URF,0210200 - SANTAREM
342,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,109698,18680,URF,0210200 - SANTAREM
426,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,117552,21303,URF,0210200 - SANTAREM
510,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,78811,17003,URF,0210200 - SANTAREM
594,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,111741,18262,URF,0210200 - SANTAREM
678,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,221170,39022,URF,0210200 - SANTAREM
762,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,182929,34536,URF,0210200 - SANTAREM
846,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,260779,47169,URF,0210200 - SANTAREM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
930,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,-,0,URF,0210200 - SANTAREM
1014,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,-,0,URF,0210200 - SANTAREM
1098,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,97312,27044,URF,0210200 - SANTAREM
1182,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,35393,4974,URF,0210200 - SANTAREM
1266,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,109698,18680,URF,0210200 - SANTAREM
1350,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,117552,21303,URF,0210200 - SANTAREM
1434,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,78811,17003,URF,0210200 - SANTAREM
1518,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,111741,18262,URF,0210200 - SANTAREM
1602,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,221170,39022,URF,0210200 - SANTAREM
1686,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,182929,34536,URF,0210200 - SANTAREM
1770,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0210200 - SANTAREM,260779,47169,URF,0210200 - SANTAREM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
7,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,33486670,9755642,URF,0217600 - PORTO DE BELEM
91,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,424820,182931,URF,0217600 - PORTO DE BELEM
175,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
259,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
343,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
427,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
511,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
595,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
679,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
763,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
847,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
931,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,33486670,9755642,URF,0217600 - PORTO DE BELEM
1015,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,424820,182931,URF,0217600 - PORTO DE BELEM
1099,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
1183,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
1267,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
1351,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
1435,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
1519,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
1603,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
1687,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM
1771,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0217600 - PORTO DE BELEM,-,0,URF,0217600 - PORTO DE BELEM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
8,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,171194882,49369367,URF,0217602 - BARCARENA
92,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,206522125,65503552,URF,0217602 - BARCARENA
176,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,268775094,76752921,URF,0217602 - BARCARENA
260,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,311292,79939,URF,0217602 - BARCARENA
344,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA
428,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA
512,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA
596,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA
680,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA
764,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA
848,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
932,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,171194882,49369367,URF,0217602 - BARCARENA
1016,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,206522125,65503552,URF,0217602 - BARCARENA
1100,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,268775094,76752921,URF,0217602 - BARCARENA
1184,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,311292,79939,URF,0217602 - BARCARENA
1268,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA
1352,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA
1436,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA
1520,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA
1604,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA
1688,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA
1772,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0217602 - BARCARENA,-,0,URF,0217602 - BARCARENA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
9,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,-,0,URF,0217800 - ALF - BELÉM
93,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,-,0,URF,0217800 - ALF - BELÉM
177,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,-,0,URF,0217800 - ALF - BELÉM
261,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,168934929,51205747,URF,0217800 - ALF - BELÉM
345,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,212218120,61879800,URF,0217800 - ALF - BELÉM
429,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,366564765,92316191,URF,0217800 - ALF - BELÉM
513,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,356144556,75765423,URF,0217800 - ALF - BELÉM
597,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,357898931,62058558,URF,0217800 - ALF - BELÉM
681,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,204536581,46318916,URF,0217800 - ALF - BELÉM
765,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,235111167,54137414,URF,0217800 - ALF - BELÉM
849,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,298530565,57578636,URF,0217800 - ALF - BELÉM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
933,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,-,0,URF,0217800 - ALF - BELÉM
1017,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,-,0,URF,0217800 - ALF - BELÉM
1101,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,-,0,URF,0217800 - ALF - BELÉM
1185,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,168934929,51205747,URF,0217800 - ALF - BELÉM
1269,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,212218120,61879800,URF,0217800 - ALF - BELÉM
1353,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,366564765,92316191,URF,0217800 - ALF - BELÉM
1437,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,356144556,75765423,URF,0217800 - ALF - BELÉM
1521,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,357898931,62058558,URF,0217800 - ALF - BELÉM
1605,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,204536581,46318916,URF,0217800 - ALF - BELÉM
1689,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,235111167,54137414,URF,0217800 - ALF - BELÉM
1773,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0217800 - ALF - BELÉM,298530565,57578636,URF,0217800 - ALF - BELÉM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
10,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
94,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
178,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
262,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
346,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
430,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,1049,147,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
514,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
598,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
682,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
766,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
850,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
934,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
1018,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
1102,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
1186,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
1270,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
1354,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,1049,147,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
1438,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
1522,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
1606,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
1690,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM
1774,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0217801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
11,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
95,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
179,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
263,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,47238550,13902354,URF,0217802 - IRF - BARCARENA
347,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
431,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
515,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
599,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
683,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
767,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
851,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
935,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
1019,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
1103,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
1187,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,47238550,13902354,URF,0217802 - IRF - BARCARENA
1271,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
1355,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
1439,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
1523,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
1607,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
1691,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA
1775,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0217802 - IRF - BARCARENA,-,0,URF,0217802 - IRF - BARCARENA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
12,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,-,0,URF,0227600 - PORTO DE MANAUS
96,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,4055689,1267843,URF,0227600 - PORTO DE MANAUS
180,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,1416252,403191,URF,0227600 - PORTO DE MANAUS
264,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,35311,5725,URF,0227600 - PORTO DE MANAUS
348,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,172012,29065,URF,0227600 - PORTO DE MANAUS
432,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,174073,31238,URF,0227600 - PORTO DE MANAUS
516,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,372650,69638,URF,0227600 - PORTO DE MANAUS
600,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,72615,12235,URF,0227600 - PORTO DE MANAUS
684,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,222195,37571,URF,0227600 - PORTO DE MANAUS
768,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,235755,46468,URF,0227600 - PORTO DE MANAUS
852,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,310794,54117,URF,0227600 - PORTO DE MANAUS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
936,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,-,0,URF,0227600 - PORTO DE MANAUS
1020,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,4055689,1267843,URF,0227600 - PORTO DE MANAUS
1104,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,1416252,403191,URF,0227600 - PORTO DE MANAUS
1188,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,35311,5725,URF,0227600 - PORTO DE MANAUS
1272,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,172012,29065,URF,0227600 - PORTO DE MANAUS
1356,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,174073,31238,URF,0227600 - PORTO DE MANAUS
1440,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,372650,69638,URF,0227600 - PORTO DE MANAUS
1524,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,72615,12235,URF,0227600 - PORTO DE MANAUS
1608,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,222195,37571,URF,0227600 - PORTO DE MANAUS
1692,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,235755,46468,URF,0227600 - PORTO DE MANAUS
1776,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0227600 - PORTO DE MANAUS,310794,54117,URF,0227600 - PORTO DE MANAUS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
13,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,2431844,2057850,URF,0230151 - BRASILEIA
97,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,2227132,1797070,URF,0230151 - BRASILEIA
181,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,1858879,1395666,URF,0230151 - BRASILEIA
265,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
349,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
433,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
517,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
601,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
685,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
769,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
853,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
937,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,2431844,2057850,URF,0230151 - BRASILEIA
1021,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,2227132,1797070,URF,0230151 - BRASILEIA
1105,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,1858879,1395666,URF,0230151 - BRASILEIA
1189,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
1273,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
1357,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
1441,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
1525,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
1609,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
1693,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA
1777,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0230151 - BRASILEIA,-,0,URF,0230151 - BRASILEIA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
14,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,-,0,URF,0230154 - Assis Brasil
98,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,217378,47300,URF,0230154 - Assis Brasil
182,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,675166,122627,URF,0230154 - Assis Brasil
266,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,1802837,376663,URF,0230154 - Assis Brasil
350,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,3849876,889536,URF,0230154 - Assis Brasil
434,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,8044124,1707944,URF,0230154 - Assis Brasil
518,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,4930866,1118167,URF,0230154 - Assis Brasil
602,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,6480600,1061434,URF,0230154 - Assis Brasil
686,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,9484761,2727094,URF,0230154 - Assis Brasil
770,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,28268836,7975455,URF,0230154 - Assis Brasil
854,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,36460920,8734810,URF,0230154 - Assis Brasil

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
938,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,-,0,URF,0230154 - Assis Brasil
1022,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,217378,47300,URF,0230154 - Assis Brasil
1106,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,675166,122627,URF,0230154 - Assis Brasil
1190,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,1802837,376663,URF,0230154 - Assis Brasil
1274,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,3849876,889536,URF,0230154 - Assis Brasil
1358,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,8044124,1707944,URF,0230154 - Assis Brasil
1442,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,4930866,1118167,URF,0230154 - Assis Brasil
1526,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,6480600,1061434,URF,0230154 - Assis Brasil
1610,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,9484761,2727094,URF,0230154 - Assis Brasil
1694,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,28268836,7975455,URF,0230154 - Assis Brasil
1778,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0230154 - Assis Brasil,36460920,8734810,URF,0230154 - Assis Brasil

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
15,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,-,0,URF,0230155 - IRF - EPITACIOLâNDIA
99,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,-,0,URF,0230155 - IRF - EPITACIOLâNDIA
183,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,-,0,URF,0230155 - IRF - EPITACIOLâNDIA
267,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,3011370,1977801,URF,0230155 - IRF - EPITACIOLâNDIA
351,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,3636955,2254410,URF,0230155 - IRF - EPITACIOLâNDIA
435,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,4396455,2660322,URF,0230155 - IRF - EPITACIOLâNDIA
519,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,4491854,2410069,URF,0230155 - IRF - EPITACIOLâNDIA
603,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,3767933,1874826,URF,0230155 - IRF - EPITACIOLâNDIA
687,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,3303051,1812218,URF,0230155 - IRF - EPITACIOLâNDIA
771,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,2386004,1151740,URF,0230155 - IRF - EPITACIOLâNDIA
855,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,944645,408420,URF,0230155 - IRF - EPITACIOLâNDIA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
939,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,-,0,URF,0230155 - IRF - EPITACIOLâNDIA
1023,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,-,0,URF,0230155 - IRF - EPITACIOLâNDIA
1107,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,-,0,URF,0230155 - IRF - EPITACIOLâNDIA
1191,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,3011370,1977801,URF,0230155 - IRF - EPITACIOLâNDIA
1275,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,3636955,2254410,URF,0230155 - IRF - EPITACIOLâNDIA
1359,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,4396455,2660322,URF,0230155 - IRF - EPITACIOLâNDIA
1443,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,4491854,2410069,URF,0230155 - IRF - EPITACIOLâNDIA
1527,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,3767933,1874826,URF,0230155 - IRF - EPITACIOLâNDIA
1611,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,3303051,1812218,URF,0230155 - IRF - EPITACIOLâNDIA
1695,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,2386004,1151740,URF,0230155 - IRF - EPITACIOLâNDIA
1779,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0230155 - IRF - EPITACIOLâNDIA,944645,408420,URF,0230155 - IRF - EPITACIOLâNDIA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
16,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
100,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
184,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
268,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
352,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
436,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
520,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
604,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
688,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
772,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
856,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0240100 - MACAPA,13592,3134,URF,0240100 - MACAPA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
940,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
1024,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
1108,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
1192,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
1276,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
1360,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
1444,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
1528,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
1612,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
1696,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0240100 - MACAPA,-,0,URF,0240100 - MACAPA
1780,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0240100 - MACAPA,13592,3134,URF,0240100 - MACAPA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
17,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
101,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
185,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
269,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
353,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
437,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
521,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
605,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
689,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,11,1,URF,0240151 - OIAPOQUE
773,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
857,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
941,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
1025,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
1109,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
1193,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
1277,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
1361,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
1445,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
1529,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
1613,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,11,1,URF,0240151 - OIAPOQUE
1697,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE
1781,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0240151 - OIAPOQUE,-,0,URF,0240151 - OIAPOQUE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
18,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0240152 - SANTANA,-,0,URF,0240152 - SANTANA
102,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0240152 - SANTANA,-,0,URF,0240152 - SANTANA
186,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0240152 - SANTANA,-,0,URF,0240152 - SANTANA
270,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0240152 - SANTANA,-,0,URF,0240152 - SANTANA
354,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0240152 - SANTANA,31573,5994,URF,0240152 - SANTANA
438,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0240152 - SANTANA,51229,9842,URF,0240152 - SANTANA
522,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0240152 - SANTANA,61282,11508,URF,0240152 - SANTANA
606,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0240152 - SANTANA,46673,7151,URF,0240152 - SANTANA
690,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0240152 - SANTANA,114442,18118,URF,0240152 - SANTANA
774,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0240152 - SANTANA,118763,20521,URF,0240152 - SANTANA
858,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0240152 - SANTANA,95046,15250,URF,0240152 - SANTANA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
942,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0240152 - SANTANA,-,0,URF,0240152 - SANTANA
1026,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0240152 - SANTANA,-,0,URF,0240152 - SANTANA
1110,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0240152 - SANTANA,-,0,URF,0240152 - SANTANA
1194,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0240152 - SANTANA,-,0,URF,0240152 - SANTANA
1278,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0240152 - SANTANA,31573,5994,URF,0240152 - SANTANA
1362,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0240152 - SANTANA,51229,9842,URF,0240152 - SANTANA
1446,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0240152 - SANTANA,61282,11508,URF,0240152 - SANTANA
1530,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0240152 - SANTANA,46673,7151,URF,0240152 - SANTANA
1614,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0240152 - SANTANA,114442,18118,URF,0240152 - SANTANA
1698,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0240152 - SANTANA,118763,20521,URF,0240152 - SANTANA
1782,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0240152 - SANTANA,95046,15250,URF,0240152 - SANTANA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
19,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO
103,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,289601,258540,URF,0250100 - PORTO VELHO
187,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,120960,112000,URF,0250100 - PORTO VELHO
271,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,65370,56000,URF,0250100 - PORTO VELHO
355,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO
439,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO
523,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO
607,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,144517,55040,URF,0250100 - PORTO VELHO
691,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO
775,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO
859,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
943,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO
1027,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,289601,258540,URF,0250100 - PORTO VELHO
1111,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,120960,112000,URF,0250100 - PORTO VELHO
1195,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,65370,56000,URF,0250100 - PORTO VELHO
1279,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO
1363,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO
1447,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO
1531,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,144517,55040,URF,0250100 - PORTO VELHO
1615,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO
1699,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO
1783,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0250100 - PORTO VELHO,-,0,URF,0250100 - PORTO VELHO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
20,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,8241929,5837918,URF,0250151 - GUAJARA-MIRIM
104,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,1844412,1330007,URF,0250151 - GUAJARA-MIRIM
188,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,1797981,1177992,URF,0250151 - GUAJARA-MIRIM
272,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,1398153,914403,URF,0250151 - GUAJARA-MIRIM
356,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,571070,397896,URF,0250151 - GUAJARA-MIRIM
440,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,3065324,2751581,URF,0250151 - GUAJARA-MIRIM
524,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,1062421,795740,URF,0250151 - GUAJARA-MIRIM
608,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,788539,481052,URF,0250151 - GUAJARA-MIRIM
692,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,959124,514856,URF,0250151 - GUAJARA-MIRIM
776,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,860299,645984,URF,0250151 - GUAJARA-MIRIM
860,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,725792,372232,URF,0250151 - GUAJARA-MIRIM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
944,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,8241929,5837918,URF,0250151 - GUAJARA-MIRIM
1028,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,1844412,1330007,URF,0250151 - GUAJARA-MIRIM
1112,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,1797981,1177992,URF,0250151 - GUAJARA-MIRIM
1196,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,1398153,914403,URF,0250151 - GUAJARA-MIRIM
1280,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,571070,397896,URF,0250151 - GUAJARA-MIRIM
1364,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,3065324,2751581,URF,0250151 - GUAJARA-MIRIM
1448,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,1062421,795740,URF,0250151 - GUAJARA-MIRIM
1532,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,788539,481052,URF,0250151 - GUAJARA-MIRIM
1616,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,959124,514856,URF,0250151 - GUAJARA-MIRIM
1700,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,860299,645984,URF,0250151 - GUAJARA-MIRIM
1784,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0250151 - GUAJARA-MIRIM,725792,372232,URF,0250151 - GUAJARA-MIRIM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
21,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,877500,150000,URF,0260151 - PACARAIMA
105,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,109339,59880,URF,0260151 - PACARAIMA
189,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,244778,163704,URF,0260151 - PACARAIMA
273,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,145632,114378,URF,0260151 - PACARAIMA
357,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,-,0,URF,0260151 - PACARAIMA
441,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,20507007,15995940,URF,0260151 - PACARAIMA
525,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,78375002,50661641,URF,0260151 - PACARAIMA
609,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,96266974,60262082,URF,0260151 - PACARAIMA
693,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,15743415,10184185,URF,0260151 - PACARAIMA
777,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,1174076,415872,URF,0260151 - PACARAIMA
861,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,588712,207936,URF,0260151 - PACARAIMA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
945,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,877500,150000,URF,0260151 - PACARAIMA
1029,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,109339,59880,URF,0260151 - PACARAIMA
1113,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,244778,163704,URF,0260151 - PACARAIMA
1197,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,145632,114378,URF,0260151 - PACARAIMA
1281,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,-,0,URF,0260151 - PACARAIMA
1365,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,20507007,15995940,URF,0260151 - PACARAIMA
1449,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,78375002,50661641,URF,0260151 - PACARAIMA
1533,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,96266974,60262082,URF,0260151 - PACARAIMA
1617,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,15743415,10184185,URF,0260151 - PACARAIMA
1701,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,1174076,415872,URF,0260151 - PACARAIMA
1785,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0260151 - PACARAIMA,588712,207936,URF,0260151 - PACARAIMA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
22,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0260152 - BONFIM,-,0,URF,0260152 - BONFIM
106,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0260152 - BONFIM,-,0,URF,0260152 - BONFIM
190,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0260152 - BONFIM,179154,114381,URF,0260152 - BONFIM
274,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0260152 - BONFIM,63567,44073,URF,0260152 - BONFIM
358,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0260152 - BONFIM,934168,554186,URF,0260152 - BONFIM
442,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0260152 - BONFIM,1083482,747226,URF,0260152 - BONFIM
526,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0260152 - BONFIM,1618505,943345,URF,0260152 - BONFIM
610,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0260152 - BONFIM,2257862,1163310,URF,0260152 - BONFIM
694,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0260152 - BONFIM,2485909,997353,URF,0260152 - BONFIM
778,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0260152 - BONFIM,7984976,3790577,URF,0260152 - BONFIM
862,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0260152 - BONFIM,16884639,7226012,URF,0260152 - BONFIM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
946,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0260152 - BONFIM,-,0,URF,0260152 - BONFIM
1030,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0260152 - BONFIM,-,0,URF,0260152 - BONFIM
1114,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0260152 - BONFIM,179154,114381,URF,0260152 - BONFIM
1198,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0260152 - BONFIM,63567,44073,URF,0260152 - BONFIM
1282,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0260152 - BONFIM,934168,554186,URF,0260152 - BONFIM
1366,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0260152 - BONFIM,1083482,747226,URF,0260152 - BONFIM
1450,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0260152 - BONFIM,1618505,943345,URF,0260152 - BONFIM
1534,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0260152 - BONFIM,2257862,1163310,URF,0260152 - BONFIM
1618,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0260152 - BONFIM,2485909,997353,URF,0260152 - BONFIM
1702,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0260152 - BONFIM,7984976,3790577,URF,0260152 - BONFIM
1786,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0260152 - BONFIM,16884639,7226012,URF,0260152 - BONFIM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
23,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,516333,188715,URF,0317800 - PORTO DE PECEM
107,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
191,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,788254,227455,URF,0317800 - PORTO DE PECEM
275,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
359,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
443,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
527,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
611,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
695,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
779,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
863,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
947,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,516333,188715,URF,0317800 - PORTO DE PECEM
1031,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
1115,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,788254,227455,URF,0317800 - PORTO DE PECEM
1199,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
1283,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
1367,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
1451,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
1535,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
1619,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
1703,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM
1787,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0317800 - PORTO DE PECEM,-,0,URF,0317800 - PORTO DE PECEM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
24,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,-,0,URF,0317900 - ALF - FORTALEZA
108,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,-,0,URF,0317900 - ALF - FORTALEZA
192,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,-,0,URF,0317900 - ALF - FORTALEZA
276,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,1010201,291742,URF,0317900 - ALF - FORTALEZA
360,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,641862,174039,URF,0317900 - ALF - FORTALEZA
444,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,1498003,410779,URF,0317900 - ALF - FORTALEZA
528,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,805422,183055,URF,0317900 - ALF - FORTALEZA
612,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,1706757,391574,URF,0317900 - ALF - FORTALEZA
696,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,1546224,335301,URF,0317900 - ALF - FORTALEZA
780,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,25600442,5380743,URF,0317900 - ALF - FORTALEZA
864,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,38949427,11050483,URF,0317900 - ALF - FORTALEZA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
948,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,-,0,URF,0317900 - ALF - FORTALEZA
1032,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,-,0,URF,0317900 - ALF - FORTALEZA
1116,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,-,0,URF,0317900 - ALF - FORTALEZA
1200,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,1010201,291742,URF,0317900 - ALF - FORTALEZA
1284,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,641862,174039,URF,0317900 - ALF - FORTALEZA
1368,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,1498003,410779,URF,0317900 - ALF - FORTALEZA
1452,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,805422,183055,URF,0317900 - ALF - FORTALEZA
1536,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,1706757,391574,URF,0317900 - ALF - FORTALEZA
1620,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,1546224,335301,URF,0317900 - ALF - FORTALEZA
1704,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,25600442,5380743,URF,0317900 - ALF - FORTALEZA
1788,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0317900 - ALF - FORTALEZA,38949427,11050483,URF,0317900 - ALF - FORTALEZA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
25,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
109,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
193,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
277,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,35577,5926,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
361,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
445,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
529,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
613,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
697,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
781,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,306180,57023,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
865,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
949,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
1033,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
1117,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
1201,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,35577,5926,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
1285,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
1369,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
1453,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
1537,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
1621,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
1705,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,306180,57023,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...
1789,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0317901 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0317901 - IRF - AEROPORTO INTERNACIONAL PINTO ...

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
26,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
110,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
194,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
278,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,82762,21277,URF,0317902 - IRF - PORTO DE PECÉM
362,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
446,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
530,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
614,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
698,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
782,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,1125,218,URF,0317902 - IRF - PORTO DE PECÉM
866,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
950,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
1034,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
1118,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
1202,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,82762,21277,URF,0317902 - IRF - PORTO DE PECÉM
1286,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
1370,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
1454,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
1538,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
1622,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM
1706,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,1125,218,URF,0317902 - IRF - PORTO DE PECÉM
1790,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0317902 - IRF - PORTO DE PECÉM,-,0,URF,0317902 - IRF - PORTO DE PECÉM

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
27,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,-,0,URF,0317903 - IRF SAO LUIS
111,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,-,0,URF,0317903 - IRF SAO LUIS
195,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,-,0,URF,0317903 - IRF SAO LUIS
279,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,-,0,URF,0317903 - IRF SAO LUIS
363,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,-,0,URF,0317903 - IRF SAO LUIS
447,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,1051490,268827,URF,0317903 - IRF SAO LUIS
531,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,1053242,246644,URF,0317903 - IRF SAO LUIS
615,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,1322500,273130,URF,0317903 - IRF SAO LUIS
699,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,1670710,336231,URF,0317903 - IRF SAO LUIS
783,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,1516820,328405,URF,0317903 - IRF SAO LUIS
867,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,1551255,328827,URF,0317903 - IRF SAO LUIS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
951,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,-,0,URF,0317903 - IRF SAO LUIS
1035,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,-,0,URF,0317903 - IRF SAO LUIS
1119,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,-,0,URF,0317903 - IRF SAO LUIS
1203,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,-,0,URF,0317903 - IRF SAO LUIS
1287,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,-,0,URF,0317903 - IRF SAO LUIS
1371,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,1051490,268827,URF,0317903 - IRF SAO LUIS
1455,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,1053242,246644,URF,0317903 - IRF SAO LUIS
1539,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,1322500,273130,URF,0317903 - IRF SAO LUIS
1623,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,1670710,336231,URF,0317903 - IRF SAO LUIS
1707,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,1516820,328405,URF,0317903 - IRF SAO LUIS
1791,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0317903 - IRF SAO LUIS,1551255,328827,URF,0317903 - IRF SAO LUIS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
28,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
112,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
196,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
280,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,149615,35593,URF,0320151 - IRF - PORTO DE SÃO LUÍS
364,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,958875,238789,URF,0320151 - IRF - PORTO DE SÃO LUÍS
448,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
532,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
616,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
700,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
784,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
868,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
952,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
1036,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
1120,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
1204,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,149615,35593,URF,0320151 - IRF - PORTO DE SÃO LUÍS
1288,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,958875,238789,URF,0320151 - IRF - PORTO DE SÃO LUÍS
1372,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
1456,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
1540,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
1624,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
1708,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS
1792,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0320151 - IRF - PORTO DE SÃO LUÍS,-,0,URF,0320151 - IRF - PORTO DE SÃO LUÍS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
29,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,2773983,1238248,URF,0417800 - PORTO DE SUAPE
113,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,2717974,1915056,URF,0417800 - PORTO DE SUAPE
197,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,8421010,3342204,URF,0417800 - PORTO DE SUAPE
281,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
365,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
449,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
533,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
617,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
701,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
785,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
869,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
953,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,2773983,1238248,URF,0417800 - PORTO DE SUAPE
1037,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,2717974,1915056,URF,0417800 - PORTO DE SUAPE
1121,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,8421010,3342204,URF,0417800 - PORTO DE SUAPE
1205,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
1289,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
1373,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
1457,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
1541,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
1625,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
1709,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE
1793,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0417800 - PORTO DE SUAPE,-,0,URF,0417800 - PORTO DE SUAPE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
30,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,-,0,URF,0417900 - ALF - RECIFE
114,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,-,0,URF,0417900 - ALF - RECIFE
198,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,-,0,URF,0417900 - ALF - RECIFE
282,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,1860,246,URF,0417900 - ALF - RECIFE
366,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,39018,8677,URF,0417900 - ALF - RECIFE
450,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,73359,15831,URF,0417900 - ALF - RECIFE
534,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,56479,9811,URF,0417900 - ALF - RECIFE
618,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,43183,7031,URF,0417900 - ALF - RECIFE
702,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,77921,14698,URF,0417900 - ALF - RECIFE
786,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,91430,18119,URF,0417900 - ALF - RECIFE
870,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,137609,21846,URF,0417900 - ALF - RECIFE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
954,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,-,0,URF,0417900 - ALF - RECIFE
1038,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,-,0,URF,0417900 - ALF - RECIFE
1122,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,-,0,URF,0417900 - ALF - RECIFE
1206,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,1860,246,URF,0417900 - ALF - RECIFE
1290,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,39018,8677,URF,0417900 - ALF - RECIFE
1374,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,73359,15831,URF,0417900 - ALF - RECIFE
1458,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,56479,9811,URF,0417900 - ALF - RECIFE
1542,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,43183,7031,URF,0417900 - ALF - RECIFE
1626,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,77921,14698,URF,0417900 - ALF - RECIFE
1710,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,91430,18119,URF,0417900 - ALF - RECIFE
1794,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0417900 - ALF - RECIFE,137609,21846,URF,0417900 - ALF - RECIFE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
31,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,-,0,URF,0417902 - IRF - PORTO DE SUAPE
115,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,-,0,URF,0417902 - IRF - PORTO DE SUAPE
199,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,-,0,URF,0417902 - IRF - PORTO DE SUAPE
283,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,993205,1071036,URF,0417902 - IRF - PORTO DE SUAPE
367,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,956766,1292389,URF,0417902 - IRF - PORTO DE SUAPE
451,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,3591587,3731786,URF,0417902 - IRF - PORTO DE SUAPE
535,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,3008864,3809945,URF,0417902 - IRF - PORTO DE SUAPE
619,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,1483441,3000837,URF,0417902 - IRF - PORTO DE SUAPE
703,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,3549968,3672016,URF,0417902 - IRF - PORTO DE SUAPE
787,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,6860820,4198485,URF,0417902 - IRF - PORTO DE SUAPE
871,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,25642351,9331354,URF,0417902 - IRF - PORTO DE SUAPE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
955,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,-,0,URF,0417902 - IRF - PORTO DE SUAPE
1039,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,-,0,URF,0417902 - IRF - PORTO DE SUAPE
1123,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,-,0,URF,0417902 - IRF - PORTO DE SUAPE
1207,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,993205,1071036,URF,0417902 - IRF - PORTO DE SUAPE
1291,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,956766,1292389,URF,0417902 - IRF - PORTO DE SUAPE
1375,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,3591587,3731786,URF,0417902 - IRF - PORTO DE SUAPE
1459,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,3008864,3809945,URF,0417902 - IRF - PORTO DE SUAPE
1543,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,1483441,3000837,URF,0417902 - IRF - PORTO DE SUAPE
1627,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,3549968,3672016,URF,0417902 - IRF - PORTO DE SUAPE
1711,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,6860820,4198485,URF,0417902 - IRF - PORTO DE SUAPE
1795,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0417902 - IRF - PORTO DE SUAPE,25642351,9331354,URF,0417902 - IRF - PORTO DE SUAPE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
32,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,-,0,URF,0420154 - IRF NATAL
116,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,-,0,URF,0420154 - IRF NATAL
200,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,-,0,URF,0420154 - IRF NATAL
284,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,240,30,URF,0420154 - IRF NATAL
368,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,5824,1089,URF,0420154 - IRF NATAL
452,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,26574,5580,URF,0420154 - IRF NATAL
536,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,15527,3108,URF,0420154 - IRF NATAL
620,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,39105,6463,URF,0420154 - IRF NATAL
704,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,42046,9053,URF,0420154 - IRF NATAL
788,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,50217,9066,URF,0420154 - IRF NATAL
872,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,35456,5615,URF,0420154 - IRF NATAL

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
956,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,-,0,URF,0420154 - IRF NATAL
1040,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,-,0,URF,0420154 - IRF NATAL
1124,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,-,0,URF,0420154 - IRF NATAL
1208,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,240,30,URF,0420154 - IRF NATAL
1292,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,5824,1089,URF,0420154 - IRF NATAL
1376,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,26574,5580,URF,0420154 - IRF NATAL
1460,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,15527,3108,URF,0420154 - IRF NATAL
1544,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,39105,6463,URF,0420154 - IRF NATAL
1628,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,42046,9053,URF,0420154 - IRF NATAL
1712,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,50217,9066,URF,0420154 - IRF NATAL
1796,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0420154 - IRF NATAL,35456,5615,URF,0420154 - IRF NATAL

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
33,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,-,0,URF,0430151 - CABEDELO
117,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,-,0,URF,0430151 - CABEDELO
201,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,-,0,URF,0430151 - CABEDELO
285,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,2306,459,URF,0430151 - CABEDELO
369,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,5627,1667,URF,0430151 - CABEDELO
453,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,29517,6676,URF,0430151 - CABEDELO
537,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,27577,5454,URF,0430151 - CABEDELO
621,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,16075,2711,URF,0430151 - CABEDELO
705,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,22026,4277,URF,0430151 - CABEDELO
789,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,26421,4794,URF,0430151 - CABEDELO
873,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,40150,6971,URF,0430151 - CABEDELO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
957,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,-,0,URF,0430151 - CABEDELO
1041,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,-,0,URF,0430151 - CABEDELO
1125,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,-,0,URF,0430151 - CABEDELO
1209,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,2306,459,URF,0430151 - CABEDELO
1293,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,5627,1667,URF,0430151 - CABEDELO
1377,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,29517,6676,URF,0430151 - CABEDELO
1461,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,27577,5454,URF,0430151 - CABEDELO
1545,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,16075,2711,URF,0430151 - CABEDELO
1629,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,22026,4277,URF,0430151 - CABEDELO
1713,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,26421,4794,URF,0430151 - CABEDELO
1797,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0430151 - CABEDELO,40150,6971,URF,0430151 - CABEDELO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
34,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0440151 - MACEIO,-,0,URF,0440151 - MACEIO
118,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0440151 - MACEIO,-,0,URF,0440151 - MACEIO
202,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0440151 - MACEIO,-,0,URF,0440151 - MACEIO
286,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0440151 - MACEIO,2563,455,URF,0440151 - MACEIO
370,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0440151 - MACEIO,83693,16567,URF,0440151 - MACEIO
454,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0440151 - MACEIO,69246,14197,URF,0440151 - MACEIO
538,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0440151 - MACEIO,54129,11415,URF,0440151 - MACEIO
622,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0440151 - MACEIO,86347,16128,URF,0440151 - MACEIO
706,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0440151 - MACEIO,78408,17224,URF,0440151 - MACEIO
790,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0440151 - MACEIO,94844,17553,URF,0440151 - MACEIO
874,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0440151 - MACEIO,134310,25356,URF,0440151 - MACEIO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
958,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0440151 - MACEIO,-,0,URF,0440151 - MACEIO
1042,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0440151 - MACEIO,-,0,URF,0440151 - MACEIO
1126,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0440151 - MACEIO,-,0,URF,0440151 - MACEIO
1210,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0440151 - MACEIO,2563,455,URF,0440151 - MACEIO
1294,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0440151 - MACEIO,83693,16567,URF,0440151 - MACEIO
1378,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0440151 - MACEIO,69246,14197,URF,0440151 - MACEIO
1462,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0440151 - MACEIO,54129,11415,URF,0440151 - MACEIO
1546,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0440151 - MACEIO,86347,16128,URF,0440151 - MACEIO
1630,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0440151 - MACEIO,78408,17224,URF,0440151 - MACEIO
1714,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0440151 - MACEIO,94844,17553,URF,0440151 - MACEIO
1798,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0440151 - MACEIO,134310,25356,URF,0440151 - MACEIO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
35,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,-,0,URF,0510353 - IRF ILHEUS
119,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,-,0,URF,0510353 - IRF ILHEUS
203,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,-,0,URF,0510353 - IRF ILHEUS
287,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,-,0,URF,0510353 - IRF ILHEUS
371,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,-,0,URF,0510353 - IRF ILHEUS
455,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,5104,1770,URF,0510353 - IRF ILHEUS
539,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,3749,1287,URF,0510353 - IRF ILHEUS
623,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,6962,1818,URF,0510353 - IRF ILHEUS
707,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,20878,5458,URF,0510353 - IRF ILHEUS
791,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,4749,1146,URF,0510353 - IRF ILHEUS
875,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,9215,1771,URF,0510353 - IRF ILHEUS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
959,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,-,0,URF,0510353 - IRF ILHEUS
1043,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,-,0,URF,0510353 - IRF ILHEUS
1127,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,-,0,URF,0510353 - IRF ILHEUS
1211,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,-,0,URF,0510353 - IRF ILHEUS
1295,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,-,0,URF,0510353 - IRF ILHEUS
1379,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,5104,1770,URF,0510353 - IRF ILHEUS
1463,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,3749,1287,URF,0510353 - IRF ILHEUS
1547,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,6962,1818,URF,0510353 - IRF ILHEUS
1631,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,20878,5458,URF,0510353 - IRF ILHEUS
1715,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,4749,1146,URF,0510353 - IRF ILHEUS
1799,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0510353 - IRF ILHEUS,9215,1771,URF,0510353 - IRF ILHEUS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
36,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
120,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
204,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
288,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,2219,1012,URF,0510552 - ILHEUS
372,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,5766,2125,URF,0510552 - ILHEUS
456,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
540,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
624,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
708,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
792,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
876,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
960,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
1044,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
1128,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
1212,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,2219,1012,URF,0510552 - ILHEUS
1296,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,5766,2125,URF,0510552 - ILHEUS
1380,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
1464,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
1548,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
1632,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
1716,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS
1800,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0510552 - ILHEUS,-,0,URF,0510552 - ILHEUS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
37,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,23123974,9435328,URF,0517600 - PORTO DE SALVADOR
121,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,16625207,6226445,URF,0517600 - PORTO DE SALVADOR
205,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,14559322,4988138,URF,0517600 - PORTO DE SALVADOR
289,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
373,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
457,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
541,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
625,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
709,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
793,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
877,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
961,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,23123974,9435328,URF,0517600 - PORTO DE SALVADOR
1045,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,16625207,6226445,URF,0517600 - PORTO DE SALVADOR
1129,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,14559322,4988138,URF,0517600 - PORTO DE SALVADOR
1213,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
1297,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
1381,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
1465,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
1549,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
1633,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
1717,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR
1801,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0517600 - PORTO DE SALVADOR,-,0,URF,0517600 - PORTO DE SALVADOR

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
38,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,-,0,URF,0517800 - ALF - SALVADOR
122,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,-,0,URF,0517800 - ALF - SALVADOR
206,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,-,0,URF,0517800 - ALF - SALVADOR
290,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,17528064,6460617,URF,0517800 - ALF - SALVADOR
374,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,11702041,4817272,URF,0517800 - ALF - SALVADOR
458,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,18371326,6890644,URF,0517800 - ALF - SALVADOR
542,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,31378055,8594310,URF,0517800 - ALF - SALVADOR
626,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,28152244,7739473,URF,0517800 - ALF - SALVADOR
710,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,15562277,4605691,URF,0517800 - ALF - SALVADOR
794,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,9720660,3005033,URF,0517800 - ALF - SALVADOR
878,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,29999941,9577960,URF,0517800 - ALF - SALVADOR

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
962,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,-,0,URF,0517800 - ALF - SALVADOR
1046,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,-,0,URF,0517800 - ALF - SALVADOR
1130,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,-,0,URF,0517800 - ALF - SALVADOR
1214,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,17528064,6460617,URF,0517800 - ALF - SALVADOR
1298,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,11702041,4817272,URF,0517800 - ALF - SALVADOR
1382,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,18371326,6890644,URF,0517800 - ALF - SALVADOR
1466,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,31378055,8594310,URF,0517800 - ALF - SALVADOR
1550,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,28152244,7739473,URF,0517800 - ALF - SALVADOR
1634,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,15562277,4605691,URF,0517800 - ALF - SALVADOR
1718,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,9720660,3005033,URF,0517800 - ALF - SALVADOR
1802,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0517800 - ALF - SALVADOR,29999941,9577960,URF,0517800 - ALF - SALVADOR

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
39,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,-,0,URF,0520100 - ARACAJU
123,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,-,0,URF,0520100 - ARACAJU
207,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,-,0,URF,0520100 - ARACAJU
291,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,1643,408,URF,0520100 - ARACAJU
375,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,14786,2027,URF,0520100 - ARACAJU
459,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,10179,2130,URF,0520100 - ARACAJU
543,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,18607,3790,URF,0520100 - ARACAJU
627,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,20776,3956,URF,0520100 - ARACAJU
711,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,22015,4267,URF,0520100 - ARACAJU
795,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,36773,6997,URF,0520100 - ARACAJU
879,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,23899,4022,URF,0520100 - ARACAJU

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
963,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,-,0,URF,0520100 - ARACAJU
1047,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,-,0,URF,0520100 - ARACAJU
1131,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,-,0,URF,0520100 - ARACAJU
1215,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,1643,408,URF,0520100 - ARACAJU
1299,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,14786,2027,URF,0520100 - ARACAJU
1383,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,10179,2130,URF,0520100 - ARACAJU
1467,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,18607,3790,URF,0520100 - ARACAJU
1551,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,20776,3956,URF,0520100 - ARACAJU
1635,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,22015,4267,URF,0520100 - ARACAJU
1719,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,36773,6997,URF,0520100 - ARACAJU
1803,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0520100 - ARACAJU,23899,4022,URF,0520100 - ARACAJU

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
40,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
124,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
208,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
292,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,26,18,URF,0617700 - ALF - BELO HORIZONTE
376,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
460,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
544,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
628,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
712,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
796,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
880,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
964,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
1048,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
1132,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
1216,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,26,18,URF,0617700 - ALF - BELO HORIZONTE
1300,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
1384,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
1468,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
1552,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
1636,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
1720,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE
1804,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0617700 - ALF - BELO HORIZONTE,-,0,URF,0617700 - ALF - BELO HORIZONTE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
41,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
125,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
209,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
293,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
377,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
461,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
545,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0710200 - NITEROI,2010,378,URF,0710200 - NITEROI
629,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
713,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0710200 - NITEROI,21872,2996,URF,0710200 - NITEROI
797,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
881,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
965,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
1049,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
1133,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
1217,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
1301,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
1385,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
1469,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0710200 - NITEROI,2010,378,URF,0710200 - NITEROI
1553,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
1637,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0710200 - NITEROI,21872,2996,URF,0710200 - NITEROI
1721,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI
1805,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0710200 - NITEROI,-,0,URF,0710200 - NITEROI

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
42,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,-,0,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
126,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,-,0,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
210,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,-,0,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
294,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,-,0,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
378,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,-,0,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
462,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,198612,42186,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
546,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,179443,39130,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
630,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,252516,51403,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
714,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,298914,62544,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
798,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,392084,73175,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
882,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,475044,76635,URF,0710251 - IRF CAMPOS DOS GOYTACAZES

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
966,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,-,0,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
1050,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,-,0,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
1134,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,-,0,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
1218,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,-,0,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
1302,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,-,0,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
1386,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,198612,42186,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
1470,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,179443,39130,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
1554,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,252516,51403,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
1638,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,298914,62544,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
1722,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,392084,73175,URF,0710251 - IRF CAMPOS DOS GOYTACAZES
1806,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0710251 - IRF CAMPOS DOS GOYTACAZES,475044,76635,URF,0710251 - IRF CAMPOS DOS GOYTACAZES

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
43,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
127,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
211,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
295,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
379,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
463,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
547,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
631,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
715,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,27581,3736,URF,0710252 - IRF MACAE
799,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
883,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,5347,748,URF,0710252 - IRF MACAE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
967,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
1051,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
1135,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
1219,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
1303,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
1387,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
1471,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
1555,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
1639,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,27581,3736,URF,0710252 - IRF MACAE
1723,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,-,0,URF,0710252 - IRF MACAE
1807,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0710252 - IRF MACAE,5347,748,URF,0710252 - IRF MACAE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
44,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
128,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
212,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
296,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,3980,1008,URF,0710400 - CAMPOS DOS GOITACAZES
380,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,149031,32278,URF,0710400 - CAMPOS DOS GOITACAZES
464,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
548,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
632,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
716,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
800,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
884,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
968,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
1052,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
1136,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
1220,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,3980,1008,URF,0710400 - CAMPOS DOS GOITACAZES
1304,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,149031,32278,URF,0710400 - CAMPOS DOS GOITACAZES
1388,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
1472,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
1556,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
1640,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
1724,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES
1808,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0710400 - CAMPOS DOS GOITACAZES,-,0,URF,0710400 - CAMPOS DOS GOITACAZES

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
45,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,124105288,32622947,URF,0717600 - PORTO DO RIO DE JANEIRO
129,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,62744442,18659585,URF,0717600 - PORTO DO RIO DE JANEIRO
213,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,58574309,20497270,URF,0717600 - PORTO DO RIO DE JANEIRO
297,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,38251953,15594762,URF,0717600 - PORTO DO RIO DE JANEIRO
381,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,69586990,29377244,URF,0717600 - PORTO DO RIO DE JANEIRO
465,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,56011207,26492066,URF,0717600 - PORTO DO RIO DE JANEIRO
549,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,62395649,32149638,URF,0717600 - PORTO DO RIO DE JANEIRO
633,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,33875227,13423418,URF,0717600 - PORTO DO RIO DE JANEIRO
717,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,23817041,10651900,URF,0717600 - PORTO DO RIO DE JANEIRO
801,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,514961214,248110049,URF,0717600 - PORTO DO RIO DE JANEIRO
885,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,305901281,121750817,URF,0717600 - PORTO DO RIO DE JANEIRO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
969,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,124105288,32622947,URF,0717600 - PORTO DO RIO DE JANEIRO
1053,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,62744442,18659585,URF,0717600 - PORTO DO RIO DE JANEIRO
1137,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,58574309,20497270,URF,0717600 - PORTO DO RIO DE JANEIRO
1221,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,38251953,15594762,URF,0717600 - PORTO DO RIO DE JANEIRO
1305,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,69586990,29377244,URF,0717600 - PORTO DO RIO DE JANEIRO
1389,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,56011207,26492066,URF,0717600 - PORTO DO RIO DE JANEIRO
1473,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,62395649,32149638,URF,0717600 - PORTO DO RIO DE JANEIRO
1557,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,33875227,13423418,URF,0717600 - PORTO DO RIO DE JANEIRO
1641,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,23817041,10651900,URF,0717600 - PORTO DO RIO DE JANEIRO
1725,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,514961214,248110049,URF,0717600 - PORTO DO RIO DE JANEIRO
1809,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0717600 - PORTO DO RIO DE JANEIRO,305901281,121750817,URF,0717600 - PORTO DO RIO DE JANEIRO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
46,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,179257,56610,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
130,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,-,0,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
214,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,211851,17438,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
298,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,-,0,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
382,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,-,0,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
466,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,-,0,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
550,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,-,0,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
634,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,380643,36968,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
718,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,122,0,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
802,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,67,14,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
886,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,33845,2075,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
970,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,179257,56610,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
1054,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,-,0,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
1138,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,211851,17438,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
1222,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,-,0,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
1306,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,-,0,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
1390,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,-,0,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
1474,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,-,0,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
1558,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,380643,36968,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
1642,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,122,0,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
1726,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,67,14,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...
1810,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0717700 - AEROPORTO INTERNACIONAL DO RIO...,33845,2075,URF,0717700 - AEROPORTO INTERNACIONAL DO RIO DE JA...

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
47,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,23670976,11313125,URF,0717800 - PORTO DE ITAGUAI
131,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,55335882,26152053,URF,0717800 - PORTO DE ITAGUAI
215,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,74557214,29477863,URF,0717800 - PORTO DE ITAGUAI
299,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,143504597,52466391,URF,0717800 - PORTO DE ITAGUAI
383,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,122563414,33913198,URF,0717800 - PORTO DE ITAGUAI
467,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,38922574,18295065,URF,0717800 - PORTO DE ITAGUAI
551,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,17472181,8630853,URF,0717800 - PORTO DE ITAGUAI
635,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,11031791,4825817,URF,0717800 - PORTO DE ITAGUAI
719,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,14146129,6561600,URF,0717800 - PORTO DE ITAGUAI
803,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,130372062,59603224,URF,0717800 - PORTO DE ITAGUAI
887,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,55750928,17947063,URF,0717800 - PORTO DE ITAGUAI

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
971,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,23670976,11313125,URF,0717800 - PORTO DE ITAGUAI
1055,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,55335882,26152053,URF,0717800 - PORTO DE ITAGUAI
1139,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,74557214,29477863,URF,0717800 - PORTO DE ITAGUAI
1223,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,143504597,52466391,URF,0717800 - PORTO DE ITAGUAI
1307,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,122563414,33913198,URF,0717800 - PORTO DE ITAGUAI
1391,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,38922574,18295065,URF,0717800 - PORTO DE ITAGUAI
1475,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,17472181,8630853,URF,0717800 - PORTO DE ITAGUAI
1559,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,11031791,4825817,URF,0717800 - PORTO DE ITAGUAI
1643,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,14146129,6561600,URF,0717800 - PORTO DE ITAGUAI
1727,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,130372062,59603224,URF,0717800 - PORTO DE ITAGUAI
1811,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0717800 - PORTO DE ITAGUAI,55750928,17947063,URF,0717800 - PORTO DE ITAGUAI

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
48,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,-,0,URF,0727600 - PORTO DE VITORIA
132,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,-,0,URF,0727600 - PORTO DE VITORIA
216,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,-,0,URF,0727600 - PORTO DE VITORIA
300,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,408813,115081,URF,0727600 - PORTO DE VITORIA
384,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1192191,293831,URF,0727600 - PORTO DE VITORIA
468,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1187458,382901,URF,0727600 - PORTO DE VITORIA
552,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1266162,306452,URF,0727600 - PORTO DE VITORIA
636,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1394121,293964,URF,0727600 - PORTO DE VITORIA
720,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1489658,313877,URF,0727600 - PORTO DE VITORIA
804,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1246659,259380,URF,0727600 - PORTO DE VITORIA
888,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1833635,342163,URF,0727600 - PORTO DE VITORIA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
972,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,-,0,URF,0727600 - PORTO DE VITORIA
1056,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,-,0,URF,0727600 - PORTO DE VITORIA
1140,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,-,0,URF,0727600 - PORTO DE VITORIA
1224,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,408813,115081,URF,0727600 - PORTO DE VITORIA
1308,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1192191,293831,URF,0727600 - PORTO DE VITORIA
1392,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1187458,382901,URF,0727600 - PORTO DE VITORIA
1476,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1266162,306452,URF,0727600 - PORTO DE VITORIA
1560,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1394121,293964,URF,0727600 - PORTO DE VITORIA
1644,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1489658,313877,URF,0727600 - PORTO DE VITORIA
1728,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1246659,259380,URF,0727600 - PORTO DE VITORIA
1812,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0727600 - PORTO DE VITORIA,1833635,342163,URF,0727600 - PORTO DE VITORIA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
49,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,-,0,URF,0812051 - SAO SEBASTIAO
133,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,-,0,URF,0812051 - SAO SEBASTIAO
217,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,-,0,URF,0812051 - SAO SEBASTIAO
301,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,83989,20657,URF,0812051 - SAO SEBASTIAO
385,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,226590,54362,URF,0812051 - SAO SEBASTIAO
469,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,324946,76087,URF,0812051 - SAO SEBASTIAO
553,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,142734,31006,URF,0812051 - SAO SEBASTIAO
637,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,162707,35400,URF,0812051 - SAO SEBASTIAO
721,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,253050,55318,URF,0812051 - SAO SEBASTIAO
805,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,284788,62488,URF,0812051 - SAO SEBASTIAO
889,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,369101,70698,URF,0812051 - SAO SEBASTIAO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
973,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,-,0,URF,0812051 - SAO SEBASTIAO
1057,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,-,0,URF,0812051 - SAO SEBASTIAO
1141,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,-,0,URF,0812051 - SAO SEBASTIAO
1225,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,83989,20657,URF,0812051 - SAO SEBASTIAO
1309,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,226590,54362,URF,0812051 - SAO SEBASTIAO
1393,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,324946,76087,URF,0812051 - SAO SEBASTIAO
1477,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,142734,31006,URF,0812051 - SAO SEBASTIAO
1561,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,162707,35400,URF,0812051 - SAO SEBASTIAO
1645,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,253050,55318,URF,0812051 - SAO SEBASTIAO
1729,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,284788,62488,URF,0812051 - SAO SEBASTIAO
1813,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0812051 - SAO SEBASTIAO,369101,70698,URF,0812051 - SAO SEBASTIAO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
50,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,11760107,1075552,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
134,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,12268340,1116363,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
218,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,15971433,1587449,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
302,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,5769393,911716,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
386,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,5193517,576773,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
470,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,1531468,159807,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
554,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,3384645,321179,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
638,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,3016311,258721,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
722,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,5033791,561028,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
806,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,3709044,414996,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
890,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,5761362,495456,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
974,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,11760107,1075552,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
1058,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,12268340,1116363,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
1142,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,15971433,1587449,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
1226,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,5769393,911716,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
1310,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,5193517,576773,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
1394,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,1531468,159807,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
1478,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,3384645,321179,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
1562,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,3016311,258721,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
1646,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,5033791,561028,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
1730,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,3709044,414996,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...
1814,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0817600 - AEROPORTO INTERNACIONAL DE SAO...,5761362,495456,URF,0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO...

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
51,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,140102,56912,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
135,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,841354,195048,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
219,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,539,29,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
303,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,41820,4065,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
387,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,765202,120572,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
471,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,470174,57493,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
555,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,36643,3917,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
639,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,264284,14191,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
723,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,37303,8269,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
807,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,3,0,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
891,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,448447,35702,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
975,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,140102,56912,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
1059,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,841354,195048,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
1143,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,539,29,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
1227,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,41820,4065,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
1311,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,765202,120572,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
1395,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,470174,57493,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
1479,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,36643,3917,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
1563,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,264284,14191,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
1647,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,37303,8269,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
1731,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,3,0,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS
1815,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0817700 - AEROPORTO INTERNACIONAL DE VIR...,448447,35702,URF,0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
52,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,3571610634,1066014651,URF,0817800 - PORTO DE SANTOS
136,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,3829225332,1186193034,URF,0817800 - PORTO DE SANTOS
220,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,4624115427,1351734374,URF,0817800 - PORTO DE SANTOS
304,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,4717069871,1385062827,URF,0817800 - PORTO DE SANTOS
388,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,5579589378,1545908728,URF,0817800 - PORTO DE SANTOS
472,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,6233639808,1706537866,URF,0817800 - PORTO DE SANTOS
556,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,7427618468,1746284912,URF,0817800 - PORTO DE SANTOS
640,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,9917489759,2021765158,URF,0817800 - PORTO DE SANTOS
724,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,7770057785,1991175235,URF,0817800 - PORTO DE SANTOS
808,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,9222261939,2388863661,URF,0817800 - PORTO DE SANTOS
892,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,11376100836,2555880358,URF,0817800 - PORTO DE SANTOS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
976,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,3571610634,1066014651,URF,0817800 - PORTO DE SANTOS
1060,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,3829225332,1186193034,URF,0817800 - PORTO DE SANTOS
1144,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,4624115427,1351734374,URF,0817800 - PORTO DE SANTOS
1228,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,4717069871,1385062827,URF,0817800 - PORTO DE SANTOS
1312,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,5579589378,1545908728,URF,0817800 - PORTO DE SANTOS
1396,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,6233639808,1706537866,URF,0817800 - PORTO DE SANTOS
1480,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,7427618468,1746284912,URF,0817800 - PORTO DE SANTOS
1564,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,9917489759,2021765158,URF,0817800 - PORTO DE SANTOS
1648,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,7770057785,1991175235,URF,0817800 - PORTO DE SANTOS
1732,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,9222261939,2388863661,URF,0817800 - PORTO DE SANTOS
1816,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0817800 - PORTO DE SANTOS,11376100836,2555880358,URF,0817800 - PORTO DE SANTOS

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
53,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,527,11,URF,0817900 - SAO PAULO
137,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
221,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
305,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
389,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
473,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
557,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
641,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
725,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
809,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
893,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
977,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,527,11,URF,0817900 - SAO PAULO
1061,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
1145,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
1229,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
1313,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
1397,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
1481,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
1565,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
1649,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
1733,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO
1817,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0817900 - SAO PAULO,-,0,URF,0817900 - SAO PAULO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
54,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,22147188,10609569,URF,0910600 - FOZ DO IGUACU
138,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,22141112,10768044,URF,0910600 - FOZ DO IGUACU
222,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,21289542,10485665,URF,0910600 - FOZ DO IGUACU
306,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
390,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
474,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
558,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
642,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
726,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
810,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
894,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
978,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,22147188,10609569,URF,0910600 - FOZ DO IGUACU
1062,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,22141112,10768044,URF,0910600 - FOZ DO IGUACU
1146,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,21289542,10485665,URF,0910600 - FOZ DO IGUACU
1230,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
1314,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
1398,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
1482,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
1566,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
1650,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
1734,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU
1818,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0910600 - FOZ DO IGUACU,-,0,URF,0910600 - FOZ DO IGUACU

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
55,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,158,79,URF,0910651 - GUAIRA
139,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
223,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,16,1,URF,0910651 - GUAIRA
307,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
391,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
475,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
559,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
643,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
727,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
811,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
895,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
979,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,158,79,URF,0910651 - GUAIRA
1063,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
1147,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,16,1,URF,0910651 - GUAIRA
1231,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
1315,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
1399,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
1483,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
1567,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
1651,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
1735,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA
1819,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0910651 - GUAIRA,-,0,URF,0910651 - GUAIRA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
56,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
140,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,281,50,URF,0915200 - CURITIBA
224,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
308,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
392,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
476,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
560,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
644,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
728,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
812,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
896,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
980,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
1064,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,281,50,URF,0915200 - CURITIBA
1148,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
1232,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
1316,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
1400,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
1484,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
1568,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
1652,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
1736,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA
1820,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0915200 - CURITIBA,-,0,URF,0915200 - CURITIBA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
57,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,-,0,URF,0917500 - ALF - FOZ DO IGUAÇU
141,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,-,0,URF,0917500 - ALF - FOZ DO IGUAÇU
225,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,-,0,URF,0917500 - ALF - FOZ DO IGUAÇU
309,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,27961439,13787316,URF,0917500 - ALF - FOZ DO IGUAÇU
393,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,49793136,17915288,URF,0917500 - ALF - FOZ DO IGUAÇU
477,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,60828554,23375942,URF,0917500 - ALF - FOZ DO IGUAÇU
561,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,137345640,40342926,URF,0917500 - ALF - FOZ DO IGUAÇU
645,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,72848295,28099865,URF,0917500 - ALF - FOZ DO IGUAÇU
729,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,71818425,27510022,URF,0917500 - ALF - FOZ DO IGUAÇU
813,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,108508774,41515396,URF,0917500 - ALF - FOZ DO IGUAÇU
897,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,159744548,53169384,URF,0917500 - ALF - FOZ DO IGUAÇU

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
981,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,-,0,URF,0917500 - ALF - FOZ DO IGUAÇU
1065,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,-,0,URF,0917500 - ALF - FOZ DO IGUAÇU
1149,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,-,0,URF,0917500 - ALF - FOZ DO IGUAÇU
1233,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,27961439,13787316,URF,0917500 - ALF - FOZ DO IGUAÇU
1317,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,49793136,17915288,URF,0917500 - ALF - FOZ DO IGUAÇU
1401,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,60828554,23375942,URF,0917500 - ALF - FOZ DO IGUAÇU
1485,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,137345640,40342926,URF,0917500 - ALF - FOZ DO IGUAÇU
1569,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,72848295,28099865,URF,0917500 - ALF - FOZ DO IGUAÇU
1653,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,71818425,27510022,URF,0917500 - ALF - FOZ DO IGUAÇU
1737,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,108508774,41515396,URF,0917500 - ALF - FOZ DO IGUAÇU
1821,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,159744548,53169384,URF,0917500 - ALF - FOZ DO IGUAÇU
1848,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0917500 - ALF - FOZ DO IGUAÇU,159744548,53169384,URF,0917500 - ALF - FOZ DO IGUAÇU

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
58,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,-,0,URF,0917501 - IRF - GUAÍRA
142,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,-,0,URF,0917501 - IRF - GUAÍRA
226,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,-,0,URF,0917501 - IRF - GUAÍRA
310,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,3343414,1191507,URF,0917501 - IRF - GUAÍRA
394,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,-,0,URF,0917501 - IRF - GUAÍRA
478,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,-,0,URF,0917501 - IRF - GUAÍRA
562,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,-,0,URF,0917501 - IRF - GUAÍRA
646,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,106096,45998,URF,0917501 - IRF - GUAÍRA
730,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,267642,82475,URF,0917501 - IRF - GUAÍRA
814,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,1466340,418541,URF,0917501 - IRF - GUAÍRA
898,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,12226051,3557541,URF,0917501 - IRF - GUAÍRA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
982,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,-,0,URF,0917501 - IRF - GUAÍRA
1066,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,-,0,URF,0917501 - IRF - GUAÍRA
1150,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,-,0,URF,0917501 - IRF - GUAÍRA
1234,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,3343414,1191507,URF,0917501 - IRF - GUAÍRA
1318,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,-,0,URF,0917501 - IRF - GUAÍRA
1402,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,-,0,URF,0917501 - IRF - GUAÍRA
1486,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,-,0,URF,0917501 - IRF - GUAÍRA
1570,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,106096,45998,URF,0917501 - IRF - GUAÍRA
1654,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,267642,82475,URF,0917501 - IRF - GUAÍRA
1738,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,1466340,418541,URF,0917501 - IRF - GUAÍRA
1822,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,12226051,3557541,URF,0917501 - IRF - GUAÍRA
1849,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0917501 - IRF - GUAÍRA,12226051,3557541,URF,0917501 - IRF - GUAÍRA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
59,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,3334646671,1791441606,URF,0917800 - PORTO DE PARANAGUA
143,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,2990190064,1732455215,URF,0917800 - PORTO DE PARANAGUA
227,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,3105229919,1691127979,URF,0917800 - PORTO DE PARANAGUA
311,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,3221577163,1753415868,URF,0917800 - PORTO DE PARANAGUA
395,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,4193388822,2104838234,URF,0917800 - PORTO DE PARANAGUA
479,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,4127443622,2196040026,URF,0917800 - PORTO DE PARANAGUA
563,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,4275061720,2234303020,URF,0917800 - PORTO DE PARANAGUA
647,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,6359985307,2539378024,URF,0917800 - PORTO DE PARANAGUA
731,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,6885397808,3030649524,URF,0917800 - PORTO DE PARANAGUA
815,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,7380132245,3174229501,URF,0917800 - PORTO DE PARANAGUA
899,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,9194994701,3466143652,URF,0917800 - PORTO DE PARANAGUA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
983,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,3334646671,1791441606,URF,0917800 - PORTO DE PARANAGUA
1067,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,2990190064,1732455215,URF,0917800 - PORTO DE PARANAGUA
1151,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,3105229919,1691127979,URF,0917800 - PORTO DE PARANAGUA
1235,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,3221577163,1753415868,URF,0917800 - PORTO DE PARANAGUA
1319,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,4193388822,2104838234,URF,0917800 - PORTO DE PARANAGUA
1403,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,4127443622,2196040026,URF,0917800 - PORTO DE PARANAGUA
1487,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,4275061720,2234303020,URF,0917800 - PORTO DE PARANAGUA
1571,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,6359985307,2539378024,URF,0917800 - PORTO DE PARANAGUA
1655,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,6885397808,3030649524,URF,0917800 - PORTO DE PARANAGUA
1739,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,7380132245,3174229501,URF,0917800 - PORTO DE PARANAGUA
1823,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,9194994701,3466143652,URF,0917800 - PORTO DE PARANAGUA
1850,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0917800 - PORTO DE PARANAGUA,9194994701,3466143652,URF,0917800 - PORTO DE PARANAGUA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
60,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
144,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
228,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
312,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,65,26,URF,0917900 - ALF - CURITIBA
396,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,262,115,URF,0917900 - ALF - CURITIBA
480,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
564,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
648,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,26,15,URF,0917900 - ALF - CURITIBA
732,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
816,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,561,214,URF,0917900 - ALF - CURITIBA
900,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
984,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
1068,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
1152,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
1236,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,65,26,URF,0917900 - ALF - CURITIBA
1320,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,262,115,URF,0917900 - ALF - CURITIBA
1404,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
1488,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
1572,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,26,15,URF,0917900 - ALF - CURITIBA
1656,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
1740,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,561,214,URF,0917900 - ALF - CURITIBA
1824,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA
1851,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0917900 - ALF - CURITIBA,-,0,URF,0917900 - ALF - CURITIBA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
61,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,220123802,56297095,URF,0920351 - DIONISIO CERQUEIRA
145,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,272652096,81032679,URF,0920351 - DIONISIO CERQUEIRA
229,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,197907542,47586291,URF,0920351 - DIONISIO CERQUEIRA
313,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
397,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
481,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
565,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
649,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
733,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
817,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
901,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
985,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,220123802,56297095,URF,0920351 - DIONISIO CERQUEIRA
1069,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,272652096,81032679,URF,0920351 - DIONISIO CERQUEIRA
1153,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,197907542,47586291,URF,0920351 - DIONISIO CERQUEIRA
1237,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
1321,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
1405,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
1489,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
1573,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
1657,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
1741,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
1825,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA
1852,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0920351 - DIONISIO CERQUEIRA,-,0,URF,0920351 - DIONISIO CERQUEIRA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
62,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,39916299,49230815,URF,0925251 - IMBITUBA
146,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,15823637,26592156,URF,0925251 - IMBITUBA
230,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,18257741,11105534,URF,0925251 - IMBITUBA
314,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
398,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
482,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
566,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
650,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
734,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
818,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
902,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
986,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,39916299,49230815,URF,0925251 - IMBITUBA
1070,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,15823637,26592156,URF,0925251 - IMBITUBA
1154,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,18257741,11105534,URF,0925251 - IMBITUBA
1238,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
1322,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
1406,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
1490,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
1574,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
1658,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
1742,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
1826,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA
1853,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0925251 - IMBITUBA,-,0,URF,0925251 - IMBITUBA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
63,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
147,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
231,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
315,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
399,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
483,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
567,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
651,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
735,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
819,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,2379,483,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
903,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
987,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
1071,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
1155,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
1239,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
1323,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
1407,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
1491,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
1575,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
1659,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
1743,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,2379,483,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
1827,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...
1854,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0927501 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,0927501 - IRF - AEROPORTO INTERNACIONAL DE FLO...

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
64,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,-,0,URF,0927502 - IRF - IMBITUBA
148,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,-,0,URF,0927502 - IRF - IMBITUBA
232,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,-,0,URF,0927502 - IRF - IMBITUBA
316,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,46091366,30767441,URF,0927502 - IRF - IMBITUBA
400,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,713446,494663,URF,0927502 - IRF - IMBITUBA
484,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,108892,28041,URF,0927502 - IRF - IMBITUBA
568,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,154081,41308,URF,0927502 - IRF - IMBITUBA
652,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,196807,48927,URF,0927502 - IRF - IMBITUBA
736,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,237119,57057,URF,0927502 - IRF - IMBITUBA
820,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,40595786,24707228,URF,0927502 - IRF - IMBITUBA
904,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,89618154,43973640,URF,0927502 - IRF - IMBITUBA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
988,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,-,0,URF,0927502 - IRF - IMBITUBA
1072,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,-,0,URF,0927502 - IRF - IMBITUBA
1156,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,-,0,URF,0927502 - IRF - IMBITUBA
1240,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,46091366,30767441,URF,0927502 - IRF - IMBITUBA
1324,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,713446,494663,URF,0927502 - IRF - IMBITUBA
1408,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,108892,28041,URF,0927502 - IRF - IMBITUBA
1492,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,154081,41308,URF,0927502 - IRF - IMBITUBA
1576,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,196807,48927,URF,0927502 - IRF - IMBITUBA
1660,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,237119,57057,URF,0927502 - IRF - IMBITUBA
1744,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,40595786,24707228,URF,0927502 - IRF - IMBITUBA
1828,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,89618154,43973640,URF,0927502 - IRF - IMBITUBA
1855,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0927502 - IRF - IMBITUBA,89618154,43973640,URF,0927502 - IRF - IMBITUBA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
65,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,2489106636,907121424,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
149,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,1952207881,863113862,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
233,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,1897726021,772687884,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
317,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,1358596880,556422444,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
401,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,910539004,380244600,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
485,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,557641484,292528623,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
569,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,968236160,498769690,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
653,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,2080200191,833026687,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
737,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,2660019588,1194559225,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
821,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,3354581694,1482083117,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
905,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,3984919198,1681517355,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
989,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,2489106636,907121424,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
1073,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,1952207881,863113862,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
1157,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,1897726021,772687884,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
1241,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,1358596880,556422444,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
1325,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,910539004,380244600,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
1409,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,557641484,292528623,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
1493,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,968236160,498769690,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
1577,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,2080200191,833026687,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
1661,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,2660019588,1194559225,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
1745,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,3354581694,1482083117,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
1829,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,3984919198,1681517355,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL
1856,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0927700 - PORTO DE SAO FRANCISCO DO SUL,3984919198,1681517355,URF,0927700 - PORTO DE SAO FRANCISCO DO SUL

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
66,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3433825258,1870767386,URF,0927800 - ITAJAI
150,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3650968689,2116118897,URF,0927800 - ITAJAI
234,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3945997714,2141217902,URF,0927800 - ITAJAI
318,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3201623599,1966354968,URF,0927800 - ITAJAI
402,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3669652266,2089314001,URF,0927800 - ITAJAI
486,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3751572548,2233770121,URF,0927800 - ITAJAI
570,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,4332244135,2212600389,URF,0927800 - ITAJAI
654,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,4471660779,1954414728,URF,0927800 - ITAJAI
738,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3421257135,1544896183,URF,0927800 - ITAJAI
822,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,2538828076,1173714407,URF,0927800 - ITAJAI
906,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3222426587,1398923016,URF,0927800 - ITAJAI

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
990,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3433825258,1870767386,URF,0927800 - ITAJAI
1074,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3650968689,2116118897,URF,0927800 - ITAJAI
1158,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3945997714,2141217902,URF,0927800 - ITAJAI
1242,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3201623599,1966354968,URF,0927800 - ITAJAI
1326,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3669652266,2089314001,URF,0927800 - ITAJAI
1410,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3751572548,2233770121,URF,0927800 - ITAJAI
1494,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,4332244135,2212600389,URF,0927800 - ITAJAI
1578,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,4471660779,1954414728,URF,0927800 - ITAJAI
1662,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3421257135,1544896183,URF,0927800 - ITAJAI
1746,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,2538828076,1173714407,URF,0927800 - ITAJAI
1830,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3222426587,1398923016,URF,0927800 - ITAJAI
1857,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0927800 - ITAJAI,3222426587,1398923016,URF,0927800 - ITAJAI

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
67,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,-,0,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
151,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,-,0,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
235,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,-,0,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
319,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,334676777,84172488,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
403,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,198036454,53493379,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
487,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,135596361,36060780,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
571,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,189141986,43226391,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
655,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,140550422,33252723,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
739,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,152563648,34737987,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
823,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,173146715,42569243,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
907,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,153088164,29751714,URF,0927900 - ALF - DIONÍSIO CERQUEIRA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
991,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,-,0,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
1075,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,-,0,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
1159,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,-,0,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
1243,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,334676777,84172488,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
1327,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,198036454,53493379,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
1411,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,135596361,36060780,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
1495,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,189141986,43226391,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
1579,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,140550422,33252723,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
1663,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,152563648,34737987,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
1747,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,173146715,42569243,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
1831,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,153088164,29751714,URF,0927900 - ALF - DIONÍSIO CERQUEIRA
1858,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 0927900 - ALF - DIONÍSIO CERQUEIRA,153088164,29751714,URF,0927900 - ALF - DIONÍSIO CERQUEIRA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
68,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,4668048,1279070,URF,1010252 - JAGUARAO
152,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,6078231,1911530,URF,1010252 - JAGUARAO
236,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,12148063,3401707,URF,1010252 - JAGUARAO
320,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,31079162,8758699,URF,1010252 - JAGUARAO
404,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,44061849,12493424,URF,1010252 - JAGUARAO
488,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,43950611,12948287,URF,1010252 - JAGUARAO
572,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,45616208,11637209,URF,1010252 - JAGUARAO
656,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,34066303,7608748,URF,1010252 - JAGUARAO
740,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,33221686,8389688,URF,1010252 - JAGUARAO
824,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,34714828,8230802,URF,1010252 - JAGUARAO
908,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,42605588,8131544,URF,1010252 - JAGUARAO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
992,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,4668048,1279070,URF,1010252 - JAGUARAO
1076,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,6078231,1911530,URF,1010252 - JAGUARAO
1160,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,12148063,3401707,URF,1010252 - JAGUARAO
1244,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,31079162,8758699,URF,1010252 - JAGUARAO
1328,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,44061849,12493424,URF,1010252 - JAGUARAO
1412,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,43950611,12948287,URF,1010252 - JAGUARAO
1496,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,45616208,11637209,URF,1010252 - JAGUARAO
1580,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,34066303,7608748,URF,1010252 - JAGUARAO
1664,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,33221686,8389688,URF,1010252 - JAGUARAO
1748,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,34714828,8230802,URF,1010252 - JAGUARAO
1832,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,42605588,8131544,URF,1010252 - JAGUARAO
1859,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1010252 - JAGUARAO,42605588,8131544,URF,1010252 - JAGUARAO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
69,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1010253 - BAGE,1261757,401432,URF,1010253 - BAGE
153,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1010253 - BAGE,36017,20159,URF,1010253 - BAGE
237,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
321,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
405,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
489,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
573,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
657,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
741,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
825,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
909,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
993,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1010253 - BAGE,1261757,401432,URF,1010253 - BAGE
1077,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1010253 - BAGE,36017,20159,URF,1010253 - BAGE
1161,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
1245,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
1329,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
1413,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
1497,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
1581,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
1665,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
1749,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
1833,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE
1860,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1010253 - BAGE,-,0,URF,1010253 - BAGE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
70,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,-,0,URF,1010351 - IRF SANTANA DO LIVRAMENTO
154,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,-,0,URF,1010351 - IRF SANTANA DO LIVRAMENTO
238,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,-,0,URF,1010351 - IRF SANTANA DO LIVRAMENTO
322,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,-,0,URF,1010351 - IRF SANTANA DO LIVRAMENTO
406,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,-,0,URF,1010351 - IRF SANTANA DO LIVRAMENTO
490,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,36915961,14388422,URF,1010351 - IRF SANTANA DO LIVRAMENTO
574,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,35916799,15401903,URF,1010351 - IRF SANTANA DO LIVRAMENTO
658,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,37267853,17322993,URF,1010351 - IRF SANTANA DO LIVRAMENTO
742,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,42305553,17684656,URF,1010351 - IRF SANTANA DO LIVRAMENTO
826,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,46627406,18690515,URF,1010351 - IRF SANTANA DO LIVRAMENTO
910,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,58893750,20686368,URF,1010351 - IRF SANTANA DO LIVRAMENTO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
994,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,-,0,URF,1010351 - IRF SANTANA DO LIVRAMENTO
1078,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,-,0,URF,1010351 - IRF SANTANA DO LIVRAMENTO
1162,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,-,0,URF,1010351 - IRF SANTANA DO LIVRAMENTO
1246,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,-,0,URF,1010351 - IRF SANTANA DO LIVRAMENTO
1330,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,-,0,URF,1010351 - IRF SANTANA DO LIVRAMENTO
1414,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,36915961,14388422,URF,1010351 - IRF SANTANA DO LIVRAMENTO
1498,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,35916799,15401903,URF,1010351 - IRF SANTANA DO LIVRAMENTO
1582,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,37267853,17322993,URF,1010351 - IRF SANTANA DO LIVRAMENTO
1666,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,42305553,17684656,URF,1010351 - IRF SANTANA DO LIVRAMENTO
1750,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,46627406,18690515,URF,1010351 - IRF SANTANA DO LIVRAMENTO
1834,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,58893750,20686368,URF,1010351 - IRF SANTANA DO LIVRAMENTO
1861,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1010351 - IRF SANTANA DO LIVRAMENTO,58893750,20686368,URF,1010351 - IRF SANTANA DO LIVRAMENTO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
71,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,33829835,10472798,URF,1010900 - URUGUAIANA
155,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,39483552,16868274,URF,1010900 - URUGUAIANA
239,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,24419315,8534603,URF,1010900 - URUGUAIANA
323,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
407,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
491,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
575,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
659,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
743,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
827,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
911,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
995,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,33829835,10472798,URF,1010900 - URUGUAIANA
1079,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,39483552,16868274,URF,1010900 - URUGUAIANA
1163,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,24419315,8534603,URF,1010900 - URUGUAIANA
1247,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
1331,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
1415,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
1499,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
1583,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
1667,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
1751,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
1835,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA
1862,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1010900 - URUGUAIANA,-,0,URF,1010900 - URUGUAIANA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
72,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,101509937,29542529,URF,1010953 - SAO BORJA
156,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,175795220,62513951,URF,1010953 - SAO BORJA
240,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,266656979,92504061,URF,1010953 - SAO BORJA
324,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
408,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
492,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
576,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
660,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
744,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
828,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
912,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
996,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,101509937,29542529,URF,1010953 - SAO BORJA
1080,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,175795220,62513951,URF,1010953 - SAO BORJA
1164,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,266656979,92504061,URF,1010953 - SAO BORJA
1248,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
1332,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
1416,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
1500,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
1584,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
1668,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
1752,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
1836,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA
1863,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1010953 - SAO BORJA,-,0,URF,1010953 - SAO BORJA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
73,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1015500 - CHUI,36398741,16202517,URF,1015500 - CHUI
157,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1015500 - CHUI,46755925,22658563,URF,1015500 - CHUI
241,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1015500 - CHUI,56448283,22945275,URF,1015500 - CHUI
325,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
409,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
493,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
577,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
661,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
745,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
829,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
913,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
997,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1015500 - CHUI,36398741,16202517,URF,1015500 - CHUI
1081,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1015500 - CHUI,46755925,22658563,URF,1015500 - CHUI
1165,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1015500 - CHUI,56448283,22945275,URF,1015500 - CHUI
1249,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
1333,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
1417,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
1501,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
1585,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
1669,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
1753,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
1837,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI
1864,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1015500 - CHUI,-,0,URF,1015500 - CHUI

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
74,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,25495585,9661444,URF,1015600 - SANTANA DO LIVRAMENTO
158,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,24036927,10331830,URF,1015600 - SANTANA DO LIVRAMENTO
242,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,29065264,10719293,URF,1015600 - SANTANA DO LIVRAMENTO
326,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
410,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
494,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
578,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
662,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
746,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
830,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
914,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
998,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,25495585,9661444,URF,1015600 - SANTANA DO LIVRAMENTO
1082,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,24036927,10331830,URF,1015600 - SANTANA DO LIVRAMENTO
1166,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,29065264,10719293,URF,1015600 - SANTANA DO LIVRAMENTO
1250,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1334,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1418,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1502,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1586,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1670,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1754,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1838,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1865,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1015600 - SANTANA DO LIVRAMENTO,-,0,URF,1015600 - SANTANA DO LIVRAMENTO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
75,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,-,0,URF,1017500 - ALF - URUGUAIANA
159,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,-,0,URF,1017500 - ALF - URUGUAIANA
243,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,-,0,URF,1017500 - ALF - URUGUAIANA
327,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,29454534,12506101,URF,1017500 - ALF - URUGUAIANA
411,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,25694256,10273352,URF,1017500 - ALF - URUGUAIANA
495,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,16153848,7366643,URF,1017500 - ALF - URUGUAIANA
579,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,31335623,11085612,URF,1017500 - ALF - URUGUAIANA
663,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,16675419,6452607,URF,1017500 - ALF - URUGUAIANA
747,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,10469797,3799676,URF,1017500 - ALF - URUGUAIANA
831,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,15853148,5993537,URF,1017500 - ALF - URUGUAIANA
915,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,32027258,10809595,URF,1017500 - ALF - URUGUAIANA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
999,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,-,0,URF,1017500 - ALF - URUGUAIANA
1083,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,-,0,URF,1017500 - ALF - URUGUAIANA
1167,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,-,0,URF,1017500 - ALF - URUGUAIANA
1251,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,29454534,12506101,URF,1017500 - ALF - URUGUAIANA
1335,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,25694256,10273352,URF,1017500 - ALF - URUGUAIANA
1419,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,16153848,7366643,URF,1017500 - ALF - URUGUAIANA
1503,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,31335623,11085612,URF,1017500 - ALF - URUGUAIANA
1587,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,16675419,6452607,URF,1017500 - ALF - URUGUAIANA
1671,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,10469797,3799676,URF,1017500 - ALF - URUGUAIANA
1755,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,15853148,5993537,URF,1017500 - ALF - URUGUAIANA
1839,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,32027258,10809595,URF,1017500 - ALF - URUGUAIANA
1866,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017500 - ALF - URUGUAIANA,32027258,10809595,URF,1017500 - ALF - URUGUAIANA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
76,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,-,0,URF,1017503 - IRF - SÃO BORJA
160,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,-,0,URF,1017503 - IRF - SÃO BORJA
244,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,-,0,URF,1017503 - IRF - SÃO BORJA
328,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,324202743,128612210,URF,1017503 - IRF - SÃO BORJA
412,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,406524579,147504720,URF,1017503 - IRF - SÃO BORJA
496,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,411837802,144924295,URF,1017503 - IRF - SÃO BORJA
580,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,654459936,216055261,URF,1017503 - IRF - SÃO BORJA
664,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,696051137,227900588,URF,1017503 - IRF - SÃO BORJA
748,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,692086017,235108168,URF,1017503 - IRF - SÃO BORJA
832,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,810613918,270508386,URF,1017503 - IRF - SÃO BORJA
916,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,1241438021,366178646,URF,1017503 - IRF - SÃO BORJA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
1000,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,-,0,URF,1017503 - IRF - SÃO BORJA
1084,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,-,0,URF,1017503 - IRF - SÃO BORJA
1168,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,-,0,URF,1017503 - IRF - SÃO BORJA
1252,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,324202743,128612210,URF,1017503 - IRF - SÃO BORJA
1336,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,406524579,147504720,URF,1017503 - IRF - SÃO BORJA
1420,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,411837802,144924295,URF,1017503 - IRF - SÃO BORJA
1504,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,654459936,216055261,URF,1017503 - IRF - SÃO BORJA
1588,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,696051137,227900588,URF,1017503 - IRF - SÃO BORJA
1672,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,692086017,235108168,URF,1017503 - IRF - SÃO BORJA
1756,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,810613918,270508386,URF,1017503 - IRF - SÃO BORJA
1840,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,1241438021,366178646,URF,1017503 - IRF - SÃO BORJA
1867,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017503 - IRF - SÃO BORJA,1241438021,366178646,URF,1017503 - IRF - SÃO BORJA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
77,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,239150,14141,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
161,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
245,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
329,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
413,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
497,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
581,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
665,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
749,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
833,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
917,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
1001,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,239150,14141,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
1085,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
1169,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
1253,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
1337,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
1421,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
1505,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
1589,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
1673,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
1757,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
1841,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE
1868,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017600 - AEROPORTO SALGADO FILHO - PORT...,-,0,URF,1017600 - AEROPORTO SALGADO FILHO - PORTO ALEGRE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
78,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,954855773,485784020,URF,1017700 - PORTO DE RIO GRANDE
162,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,812252683,442010608,URF,1017700 - PORTO DE RIO GRANDE
246,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,822709279,409190491,URF,1017700 - PORTO DE RIO GRANDE
330,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,840885987,442083878,URF,1017700 - PORTO DE RIO GRANDE
414,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1012198441,486725696,URF,1017700 - PORTO DE RIO GRANDE
498,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1136343434,531338603,URF,1017700 - PORTO DE RIO GRANDE
582,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1063427179,482999234,URF,1017700 - PORTO DE RIO GRANDE
666,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1122084936,480680521,URF,1017700 - PORTO DE RIO GRANDE
750,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1273713767,571383157,URF,1017700 - PORTO DE RIO GRANDE
834,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1276345725,575897435,URF,1017700 - PORTO DE RIO GRANDE
918,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1120114746,454125456,URF,1017700 - PORTO DE RIO GRANDE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
1002,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,954855773,485784020,URF,1017700 - PORTO DE RIO GRANDE
1086,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,812252683,442010608,URF,1017700 - PORTO DE RIO GRANDE
1170,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,822709279,409190491,URF,1017700 - PORTO DE RIO GRANDE
1254,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,840885987,442083878,URF,1017700 - PORTO DE RIO GRANDE
1338,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1012198441,486725696,URF,1017700 - PORTO DE RIO GRANDE
1422,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1136343434,531338603,URF,1017700 - PORTO DE RIO GRANDE
1506,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1063427179,482999234,URF,1017700 - PORTO DE RIO GRANDE
1590,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1122084936,480680521,URF,1017700 - PORTO DE RIO GRANDE
1674,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1273713767,571383157,URF,1017700 - PORTO DE RIO GRANDE
1758,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1276345725,575897435,URF,1017700 - PORTO DE RIO GRANDE
1842,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1120114746,454125456,URF,1017700 - PORTO DE RIO GRANDE
1869,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017700 - PORTO DE RIO GRANDE,1120114746,454125456,URF,1017700 - PORTO DE RIO GRANDE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
79,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,-,0,URF,1017701 - IRF - CHUÍ
163,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,-,0,URF,1017701 - IRF - CHUÍ
247,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,-,0,URF,1017701 - IRF - CHUÍ
331,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,65346637,31293407,URF,1017701 - IRF - CHUÍ
415,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,107878137,41483484,URF,1017701 - IRF - CHUÍ
499,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,116693634,42471461,URF,1017701 - IRF - CHUÍ
583,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,125730834,42895255,URF,1017701 - IRF - CHUÍ
667,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,158222716,51310637,URF,1017701 - IRF - CHUÍ
751,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,173777248,57354844,URF,1017701 - IRF - CHUÍ
835,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,187367985,58064792,URF,1017701 - IRF - CHUÍ
919,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,262317068,70240574,URF,1017701 - IRF - CHUÍ

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
1003,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,-,0,URF,1017701 - IRF - CHUÍ
1087,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,-,0,URF,1017701 - IRF - CHUÍ
1171,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,-,0,URF,1017701 - IRF - CHUÍ
1255,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,65346637,31293407,URF,1017701 - IRF - CHUÍ
1339,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,107878137,41483484,URF,1017701 - IRF - CHUÍ
1423,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,116693634,42471461,URF,1017701 - IRF - CHUÍ
1507,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,125730834,42895255,URF,1017701 - IRF - CHUÍ
1591,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,158222716,51310637,URF,1017701 - IRF - CHUÍ
1675,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,173777248,57354844,URF,1017701 - IRF - CHUÍ
1759,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,187367985,58064792,URF,1017701 - IRF - CHUÍ
1843,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,262317068,70240574,URF,1017701 - IRF - CHUÍ
1870,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,262317068,70240574,URF,1017701 - IRF - CHUÍ

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
80,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,-,0,URF,1017800 - ALF - PORTO ALEGRE
164,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,-,0,URF,1017800 - ALF - PORTO ALEGRE
248,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,-,0,URF,1017800 - ALF - PORTO ALEGRE
332,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,15871,4162,URF,1017800 - ALF - PORTO ALEGRE
416,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,80013,19094,URF,1017800 - ALF - PORTO ALEGRE
500,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,89009,20805,URF,1017800 - ALF - PORTO ALEGRE
584,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,63515,13752,URF,1017800 - ALF - PORTO ALEGRE
668,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,84988,13952,URF,1017800 - ALF - PORTO ALEGRE
752,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,117276,21599,URF,1017800 - ALF - PORTO ALEGRE
836,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,101051,19162,URF,1017800 - ALF - PORTO ALEGRE
920,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,128546,19740,URF,1017800 - ALF - PORTO ALEGRE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
1004,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,-,0,URF,1017800 - ALF - PORTO ALEGRE
1088,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,-,0,URF,1017800 - ALF - PORTO ALEGRE
1172,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,-,0,URF,1017800 - ALF - PORTO ALEGRE
1256,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,15871,4162,URF,1017800 - ALF - PORTO ALEGRE
1340,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,80013,19094,URF,1017800 - ALF - PORTO ALEGRE
1424,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,89009,20805,URF,1017800 - ALF - PORTO ALEGRE
1508,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,63515,13752,URF,1017800 - ALF - PORTO ALEGRE
1592,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,84988,13952,URF,1017800 - ALF - PORTO ALEGRE
1676,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,117276,21599,URF,1017800 - ALF - PORTO ALEGRE
1760,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,101051,19162,URF,1017800 - ALF - PORTO ALEGRE
1844,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,128546,19740,URF,1017800 - ALF - PORTO ALEGRE
1871,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,128546,19740,URF,1017800 - ALF - PORTO ALEGRE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
81,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
165,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
249,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
333,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
417,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,16688,987,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
501,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,10265,622,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
585,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
669,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,30,30,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
753,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,909,168,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
837,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,631,96,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
921,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
1005,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
1089,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
1173,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
1257,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
1341,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,16688,987,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
1425,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,10265,622,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
1509,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
1593,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,30,30,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
1677,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,909,168,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
1761,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,631,96,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
1845,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
1872,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,0,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
82,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
166,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
250,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
334,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,28727514,12297084,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
418,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,48829672,18859377,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
502,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
586,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
670,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
754,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
838,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
922,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
1006,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
1090,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
1174,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
1258,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,28727514,12297084,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
1342,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,48829672,18859377,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
1426,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
1510,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
1594,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
1678,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
1762,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
1846,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
1873,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,0,URF,1017900 - ALF - SANTANA DO LIVRAMENTO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
83,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
167,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
251,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
335,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
419,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
503,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
587,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
671,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
755,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
839,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
923,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,16687,55,URF,9999999 - NAO INFORMADO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
1007,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
1091,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
1175,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
1259,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
1343,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
1427,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
1511,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
1595,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
1679,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
1763,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,-,0,URF,9999999 - NAO INFORMADO
1847,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,16687,55,URF,9999999 - NAO INFORMADO
1874,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,16687,55,URF,9999999 - NAO INFORMADO